
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: $podName
  name: $podName
  namespace: $networkName
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: $podName
    spec:
      containers:
      - name: $podName
        image: fiscoorg/front:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8545
        - containerPort: 20200
        - containerPort: 30300
        - containerPort: 5002
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: peerdata
          subPath: $conf
        - mountPath: /dist/log
          name: peerdata
          subPath: $frontlog
        - mountPath: /dist/conf/application.yml
          name: peerdata
          subPath: $appconf
        workingDir: /data
      restartPolicy: Always
      volumes:
      - name: peerdata
        persistentVolumeClaim:
           claimName: $dataPV
status: {}
