
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $dataPV
  labels:
    app: $dataPV
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $dataPath
    server: $nfsServer

