
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $networkName
 name: $dataPV
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
 selector:
   matchLabels:
     app: $dataPV
